### ISSUE TITLE
Merging linux branch into master

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#1]
Merging the [linux branch](https://github.com/civctp2/civctp2/tree/linux) into master is a long standing issue. @ptitSeb 's contributions (https://github.com/civctp2/civctp2/commit/a9981554a94a55f0ebc0d31f579f0af336a8d5b1) made it possible to compile and run the game under linux with all the fancy contributions and added features that were made to the original svn-trunk, now the [master branch](https://github.com/civctp2/civctp2/tree/master). Those contributions were either specific for the windows build or OS independent. On the other hand the linux branch since https://github.com/civctp2/civctp2/commit/d78e78a86daa5c967f50effb81d004e75734b0d8 exhibited no crashes or bugs any more but lacks most OS independent additions and new features. There have been attempts to merge contributions specific to the linux port into trunk/master but up to now are not finished.
For example, ctp2@[97d6973e599eaf](https://github.com/civctp2/civctp2/tree/97d6973e599eafc5fb8ef9602c0218ad83738f84) does not yet support saving user settings (e.g. screen resolution) and games in the user home path (e.g. ~/.civctp2, as common under linux) which is implemented in the linux branch since commit [1ae3e1381c39a8c](https://github.com/civctp2/civctp2/commit/1ae3e1381c39a8c20baa55204d7657cec65d6654). Other things like the possibility of entering a file name for saving a game, avoiding crashes when loading a game, videos in the game etc. are in the linux branch and are missing in master.
However, it seems that most code in the linux branch has either become obsolete due to (OS independent) changes in master or has already been merged/incorporated. Therefore, the least effort seems to be cherry-picking (parts of) commits from the linux branch instead of doing a full merge with e.g. [git-imerge](https://github.com/mhagger/git-imerge), which would be a good approach for a full merge.

Contributions are welcome! For that, just follow the common GitHub approach of forking https://github.com/civctp2/civctp2/ from within your user profile and experiment and commit to that until your code is ready for contribution by creating a GitHub Pull Request (PR) to draw attention to your work and to discuss merging.

Contributions to the linux branch of old (to SVN) were discussed on apolyton.net in the forum ["COMPILE: Linux Port"](https://apolyton.net/forum/other-games/call-to-power-2/ctp2-source-code-project/117289-compile-linux-port).

**Comment by LynxAbraxas** [comment]
From https://github.com/civctp2/civctp2/issues/2#issuecomment-456553715
> To merge the Linux branch properly, I think I have to do the brute force method: To go through every file and merge manually what I think is was merging. That is quite some work, so for me it is a nightmare to have branches laying around in this project. Of course, it would have been our burden to make the game compile on Windows again, with the Linux changes that may occasionally break things on Windows. But it would have been the minor costs.

It depends, when going through the old SVN commits in master, I found that much code from the linux branch was already ported to master which made me consider git cherry-picking to be more effective than (my former idea of) trying to merge all commits from linux branch to master, for which [git-imerge](https://github.com/mhagger/git-imerge) would probably be very helpful and which @DEVoytas already tried. 
@DEVoytas can you give some info on this? I can't find your old comments on this.

Apart from that I'm not sure if we are missing anything important from the linux branch except a solution to the random-segfault (proabably concerning SDL) #30, and I am also not sure if the linux branch does not suffer the same problem, since the code investigated in https://github.com/LynxAbraxas/civctp2/tree/debug-random-segfaults in particular
https://github.com/LynxAbraxas/civctp2/commit/a6998b7b264da780e21c2500238dca45b4185021
https://github.com/LynxAbraxas/civctp2/commit/6a96bd28cb425fb09bdcde718b0878454d39f698
are from the linux branch.
Some things are even better solved for linux in the master branch than in the linux branch like the screen mode/resolution setting with SDL.

I agree that having a long diverged branch like the linux branch isn't good because newcomers might build work on that instead of master. I'm not sure if there is a way at GH to lock a branch for such a case. Another option would be to rename the branch to e.g. something like `linux_to_merge_use_master_for_new_contributions` which should ring a bell for any who plans to contribute. Or the linux branch tip could be given a tag  `linux_to_merge_use_master_for_new_contributions` and then the branch can be removed without loosing the commits but it will not be listed as a branch any more.

**Comment by MartinGuehmann** [comment]
> It depends, when going through the old SVN commits in master, I found that much code from the linux branch was already ported to master which made me consider git cherry-picking to be more effective than (my former idea of) trying to merge all commits from linux branch to master, for which [git-imerge](https://github.com/mhagger/git-imerge) would probably be very helpful and which @DEVoytas already tried.

See pull request #62, most of it is MBCHAR* to const MBCHAR*, when I looked through afterwards most of it was indeed just that. One memory leak, that is good to have, and one point there was a deletion of an if statement that guarded a PlaySound, so the sound was played without the condition. This is 8a1c7bb. But I stumbled upon it via something else.

Then we have the changes in aui_mouse, aui_movie, and aui_music. Then there is commit cf9f579, were I also put something in from the Linux branch, as far as I can see it is about finding the CD and also about the Linux home directory. As far as I can see it is incomplete. I even had to debug it to make it find the video directory on my CD. Debugging is not so nice without a debugger, adding every sprintf or cout is a pain in the ass. That is also something that is missing and if you wanna fix bugs on Linux, you just need it. I can fix bugs you have on Windows with the debugger of Visual Studio, that's actual why I found the problem with the CityData copying so quickly. I see it crashes on the Final version, just switch to the debug version and see what's wrong. Actually, the problem with the copy constructor is not so trival to pin down, but much better than cout everywhere.

> @DEVoytas can you give some info on this? I can't find your old comments on this.
> 
> Apart from that I'm not sure if we are missing anything important from the linux branch except a solution to the random-segfault (proabably concerning SDL) #30, and I am also not sure if the linux branch does not suffer the same problem, since the code investigated in https://github.com/LynxAbraxas/civctp2/tree/debug-random-segfaults in particular
> [LynxAbraxas@a6998b7](https://github.com/LynxAbraxas/civctp2/commit/a6998b7b264da780e21c2500238dca45b4185021)
> [LynxAbraxas@6a96bd2](https://github.com/LynxAbraxas/civctp2/commit/6a96bd28cb425fb09bdcde718b0878454d39f698)
> are from the linux branch.
> Some things are even better solved for linux in the master branch than in the linux branch like the screen mode/resolution setting with SDL.

Yes, it is code from the Linux branch, but I changed the DirectX counterpart. DirectX did not double buffer the graphics, I think it has an option for it but it did not work. All the thinks that needed to be painted were painted on the buffer that is shown. So first paint it black and than put everything on it. And have that flicker that is very tiring for me. So I added a secondary buffer. So first paint everything needed onto it and once done show it. The master branch got at some time an update to reflect, the Linux branch did not. So, I must assume that this change wasn't tested, properly. But amazingly it compiles. Actually, I found something in aui_movie, were still something was painted onto the primary.

So if it has something to do with the mutex lock then my guess it is related. For that you can also try out the changes in #62. Or shall I just merge them immediately?

> I agree that having a long diverged branch like the linux branch isn't good because newcomers might build work on that instead of master. I'm not sure if there is a way at GH to lock a branch for such a case. Another option would be to rename the branch to e.g. something like `linux_to_merge_use_master_for_new_contributions` which should ring a bell for any who plans to contribute. Or the linux branch tip could be given a tag `linux_to_merge_use_master_for_new_contributions` and then the branch can be removed without loosing the commits but it will not be listed as a branch any more.

Yes, that is another reason, I consider it as a dead branch that shouldn't receive any updates, unless that are some things added the VS project files so that I can browse it with VS 2017. I consider this useful if I wanna grab stuff for master from it. Other things may be, like making it compile with a newer version of a compiler so that you can still see it in action. For instance I could see if I can use the shift to type something in upper case, which I couldn't before #62. Of course, eventually, you like to lock this branch, but only if we have the important stuff in.

That are:
Debugging
Music plays from the CD
Videos play from the CD
Linux uses the home directory to store the data, e.g. save games

**Comment by DEVoytas** [comment]
> It depends, when going through the old SVN commits in master, I found that much code from the linux branch was already ported to master which made me consider git cherry-picking to be more effective than (my former idea of) trying to merge all commits from linux branch to master, for which [git-imerge](https://github.com/mhagger/git-imerge) would probably be very helpful and which @DEVoytas already tried.
> @DEVoytas can you give some info on this? I can't find your old comments on this.

@LynxAbraxas, perhaps you mean this comment: https://github.com/civctp2/civctp2/issues/4#issuecomment-429668935

But since linux and master branches diverged so much and at the same time much of the code from linux branch is already in master (as you pointed out) I would probably also be in favor of cherry-picking than merging, as it would likely provide cleaner results.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Is there anything left to port or would you say this issue can be closed?

**Comment by MartinGuehmann** [comment]
Well basically I reviewed the files manually. I think I checked 200 files or so. One thing that is not complete is the const cleanup, at least this I would consider to be useful. In principle, there could also be some little fixes here and there that I couldn't catch.

So we could close this and replace the issue with a const fix issue.

**Comment by LynxAbraxas** [comment]
Opened #144.

**Comment by LynxAbraxas** [comment]
Many thanks @MartinGuehmann and @ptitSeb for all your work on this.
