### ISSUE TITLE
Pirating state of trade routes not saved/loaded

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#131]
Now that #127 is in, it seems that the pirating states of trade routes are not saved/loaded. E.g. when pirating in the test-game of #75, ending the turn then the trade manager shows the pirating color orange. However when saving and re-loading that game, the pirating column color is back to white. 
Same holds for the action: pirating in the test-game then save and load before ending the turn will lead to no pirating for blue in the next turn.
I'd guess that the `m_piratingArmy` from 
https://github.com/civctp2/civctp2/blob/0668dd199c2519ff8ab7d2871e7c7a89e21c8e52/ctp2_code/gs/gameobj/TradeRouteData.cpp#L618-L621
is not saved, not sure about `m_isPirating` here
https://github.com/civctp2/civctp2/blob/0668dd199c2519ff8ab7d2871e7c7a89e21c8e52/ctp2_code/gs/gameobj/ArmyData.cpp#L508
at least allown this would not be enough since `IsBeingPirated` needs  `m_piratingArmy`
https://github.com/civctp2/civctp2/blob/0668dd199c2519ff8ab7d2871e7c7a89e21c8e52/ctp2_code/gs/gameobj/TradeRouteData.cpp#L628-L631
@MartinGuehmann What do you think?

**Comment by MartinGuehmann** [comment]
The problem is that m_piratingArmy is not saved.

https://github.com/civctp2/civctp2/blob/0668dd199c2519ff8ab7d2871e7c7a89e21c8e52/ctp2_code/gs/gameobj/TradeRouteData.cpp#L376-L461

You can reuse the slot of m_path_selection_state, it also occupies 32 bits like Army.

So you have to replace the lines

archive.PutSINT32(m_path_selection_state);
m_path_selection_state = archive.GetSINT32();

by

m_piratingArmy.Serialize(archive);

each.

Possible values for m_path_selection_state are 0, 1, and 2. Actually, it is also somewhere in the code set, but it is not used. So it shouldn't be a problem to reuse the spot. 0, 1, and 2 are not valid IDs for armies, IsValid should care about it.

**Comment by LynxAbraxas** [comment]
Solved with #132, many thanks @MartinGuehmann.
