### ISSUE TITLE
Breaking no-piracy treaty not possible

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#152]
It seems that currently it is not possible to break a no-piracy treaty, not even by declaring war. @MartinGuehmann could it be that this was broken by the remedy to #75: #127?

I get the message that ask me if I want to break the treaty with the Incans, but clicking yes has no effect:

![ss_2019-06-20_23:50:11](https://user-images.githubusercontent.com/21012234/59884684-5ec96300-93b9-11e9-99e3-899c7a7cbe11.png)

The order to pirate comes here in case of a no-piracy treaty
https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_code/gs/gameobj/ArmyData.cpp#L5911-L5927
which then leads to here
https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_data/default/gamedata/script.slc#L1465
where I wonder if the remedy in #127 now prevents that order to be executed. However, since the order is not bound to a change in position, this should not be the case.
Any idea what could be the problem?

**Comment by MartinGuehmann** [comment]
> It seems that currently it is not possible to break a no-piracy treaty, not even by declaring war. @MartinGuehmann could it be that this was broken by the remedy to #75: #127?
> 
> I get the message that ask me if I want to break the treaty with the Incans, but clicking yes has no effect:
> 
> ![ss_2019-06-20_23:50:11](https://user-images.githubusercontent.com/21012234/59884684-5ec96300-93b9-11e9-99e3-899c7a7cbe11.png)

So whose route are you trying to pirate? One from the Incas? The message doesn't tell me that it is from the Incas it just says "that nation".

> The order to pirate comes here in case of a no-piracy treaty
> https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_code/gs/gameobj/ArmyData.cpp#L5911-L5927
> 
> 
> which then leads to here

Well, important is also the line before, which should break the treaty.

https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_data/default/gamedata/script.slc#L1464-L1465
> 
> 
> where I wonder if the remedy in #127 now prevents that order to be executed. However, since the order is not bound to a change in position, this should not be the case.
> Any idea what could be the problem?

For now, I would say unrelated and even if it is, we still would need to figure out the problem. Since, you mentioned that the treaty isn't broken if you declare war then it seems to be a deeper problem.

**Comment by LynxAbraxas** [comment]
> So whose route are you trying to pirate? One from the Incas? The message doesn't tell me that it is from the Incas it just says "that nation".

Sorry, yes from the Incans, which have the pirate flag in the diplomacy manager.

**Comment by LynxAbraxas** [comment]
While comparing
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/slic/slicfunc.cpp#L4472-L4515
and
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/slic/slicfunc.cpp#L4517-L4558

I started to wonder why it is 
`AGREEMENT_TYPE_DEMAND_LEAVE_OUR_LANDS` and `REQUEST_TYPE_DEMAND_LEAVE_OUR_LANDS` 
while for piracy it seems to be  
`AGREEMENT_TYPE_NO_PIRACY` and `REQUEST_TYPE_DEMAND_NO_PIRACY`

**Comment by LynxAbraxas** [comment]
>  but clicking yes has no effect

Or closes and reopens the window.

**Comment by MartinGuehmann** [comment]
> Sorry, yes from the Incans, which have the pirate flag in the diplomacy manager.

So it stays there, when you have declared war?

Or does go away and you still cannot pirate that trade route?

**Comment by MartinGuehmann** [comment]
> I started to wonder why it is
> `AGREEMENT_TYPE_DEMAND_LEAVE_OUR_LANDS` and `REQUEST_TYPE_DEMAND_LEAVE_OUR_LANDS`
> while for piracy it seems to be
> `AGREEMENT_TYPE_NO_PIRACY` and `REQUEST_TYPE_DEMAND_NO_PIRACY`

What do you mean? Do you wonder why it is not AGREEMENT_TYPE_DEMAND_NO_PIRACY? Well, I assume the developers did not agree on a naming convention, before they started working on the code.

I just worry what context->GetPlayer(1) returns if no player is in the context. Is it -1 or 32 or whatever? "if(!g_player[context->GetPlayer(1)])" is not defined if context->GetPlayer(1)] returns -1. It shouldn't crash, because you don't dereference a pointer.

**Comment by LynxAbraxas** [comment]
> So it stays there, when you have declared war?

Yes it stays there even when under war:

![ss_2019-06-20_23:27:57](https://user-images.githubusercontent.com/21012234/59968939-b5ae7400-9542-11e9-9a2f-0d7f11cb3ba3.png)

> Well, I assume the developers did not agree on a naming convention, before they started working on the code.

I see.

**Comment by MartinGuehmann** [comment]
> > So it stays there, when you have declared war?
> 
> Yes it stays there even when under war:

Then, that seems to go deeper.
