### ISSUE TITLE
Convert old branches to tags

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#85]
There are still quite a few branches on https://github.com/civctp2/civctp2/branches, some are very old and remainders of the SVN import. To avoid others basing contribution on those but to still keep a ref on them (to avoid loosing the commits), I would suggest to convert the branches:
```
RolandTaverner
ScottGrant
linux-merge
linux-rework
port-trunk
trunk
```
into tags (possibly without a message, such that they are not regarded as releases by GH). This might even be appropriate for:
```
SaveGameConverter
linux
```
as they can be converted back to a brach if necessary.

**Comment by MartinGuehmann** [comment]
I just don't know how to convert them to tags, I can create tags on GitHub and I can delete branches on GitHub, too.

For sure those can go:

```
ScottGrant
linux-merge
linux-rework
port-trunk
trunk
```
I think ScottGrant just contains one commit. The linux and port trunk are linux branch merge attempts. Then we still have:

```
RolandTaverner
SaveGameConverter
linux
```
For the linux branch, I still don't know whether I have everything, but that seems to be of low importance. Then there is something left from the RolandTaverner branch. Basically, that are the Visual Project files, that might contain something. There seems to have happened something with them. In master, we have the project files in I converted from my VS 2008 project files, the ones in the branch RolandTaverner have been created independently.

Unfortunately, the project configurations are in a different order so that I cannot just compare them with a merge/diff program. So the task would be to reorder the stuff so that I can compare, and then pick what seems to be good. That would be at least one final commit to that branch. But it has also low priority.

Then we have SaveGameConverter, with pull request #89 in mind I wouldn't be so sure if nothing would come anymore.

**Comment by LynxAbraxas** [comment]
> I just don't know how to convert them to tags, I can create tags on GitHub and I can delete branches on GitHub, too.

Basiacally you would create a tag pointing to the corresponding branch tip first, then delete the branch, using the GH UI is probably the best.

**Comment by MartinGuehmann** [comment]
Through GitHub it is a bit ugly, basically you have to create a release and if you wanna have it just a tag then you delete the release and the tag is left. For now I created tags for the following branches:

```
linux-merge
linux-rework
port-trunk
trunk
```

I still wanna look at ScottGrant's branch.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann: I just had the idea that you can actually create a PR from civctp2 to itself, like a PR of ScottGrant to master. That will allow you to discuss what you want to include and what you already have and what you decided not to.
When you think all is finished in direct commits or merges of other PRs you can just close the PR by deleting the branch. As far as I know (but better check the GH docs before) the created PR will keep a pointer to the former branch tip, a kind of hidden tag or branch, special for GH, so the orig commits will not be lost and the PR can be re-opened later if interest arises.
